### DISCUSSION TITLE
ECUB data is reset every night to the value of the night before.

### DISCUSSION THREAD

**Discussion by HAEdwin** [HAEdwin/homeassistant-apsystems_ecu_reader#10] [General]
ECUB data is reset every night to the value of the night before. In my case it is reset every night to 600 kWh.

This gives me a negative yield in HA every morning.

If I connect directly to the ECUB I see that the value there also starts at 600 every day.

So this is a problem with the ECUB and not with the HA integration.

I have reported this to APSystemsema but I don't think they will do anything about it.

Now I wonder if more people are experiencing these problems.

**Comment by Woetter22** [comment]
https://github.com/ksheumaker/homeassistant-apsystems_ecur/discussions/284#discussioncomment-12344827

![image](https://github.com/user-attachments/assets/def4c5c2-2430-4449-9c3e-9b34ddaf1e5e)

After the advice to redownload the package and then replace the sensor.py the error messages are gone.

When the sun shines I am unfortunately not at home so I hope I have the chance to log in remotely today.

**Reply by Woetter22** [reply]
![image](https://github.com/user-attachments/assets/e3348987-6d18-4ffc-923e-b0344caed92c)
the results of today

**Reply by HAEdwin** [reply]
Today Energy is not equal with Lifetime Energy Produced - do you know why Today Energy is zero?

**Reply by Woetter22** [reply]
Today's energy is always zero for me since the daily resets started
In the ECU it is always set to 0.
![image](https://github.com/user-attachments/assets/a46e06ad-cacc-4ece-86e2-2e82d41f119b)

**Reply by TexTown** [reply]
I think the daily reset of 'Lifetime Energy' and 'Today Energy'  being 0 all the time are both firmware issues.
I have both issues as well, but on an ECU_R running FW version 1.2.31

**Reply by Woetter22** [reply]
I think so too, these are purely firmware issues.

**Comment by HAEdwin** [comment]
@TexTown From your last screendump I can see that the Lifetime Energy is not being reset and the previous screendump suggests that it is the Lifetime Energy but are you sure you didn't label it wrong? Isn't that the Today Energy entity? @Woetter22  you might want to take a look at this also, I didn't thought of that earlier but the label and entity ID might not match up.

**Reply by TexTown** [reply]
![image](https://github.com/user-attachments/assets/ad0d125b-dfa8-441e-849c-a77a5bc9e8d9)

This is a screenshot from the integration, not some dashboard or card I made myself.
So the sensor names are right. The 'Lifetime Energy' is increasing during the day, but just like @Woetter22 is experiencing 'Lifetime Energy' is reset at 4:00 AM (or around that time) each night, back to 18,967.3 kWh

![image](https://github.com/user-attachments/assets/7afe83be-3e11-4b3f-990b-ce26b47e2413)

The 0 value for 'Today Enrgy' is a long standing firmware bug.

**Reply by HAEdwin** [reply]
Oh yes, I see now - forgot about the state not returning to zero but to 18,967.3. Clear now thanx.

**Reply by TexTown** [reply]
![image](https://github.com/user-attachments/assets/9d671a10-f81d-4363-9e16-dbcd35dff3fe)

Iv'e been using utility_meter sensors (based on the 'Lifetime Energy' ) to calculate daily (but also monthly and yearly) solar usage.
So I'm working around the 'Today Energy' being 0 all the time.

**Reply by HAEdwin** [reply]
Yeah, it's a great integration but there's no "lifetime" cycle option from what I understand. I asked Diogo Gomes if it is currently possible to create a lifetime sensor and if not, would it be possible to add the "lifetime" cycle option. 

Reason for me asking this is because I realize that for 98% of the users, the additional lifetime_enery_produced sensor might not add anything - so I really have to explain why this sensor is introduced in the next release. The lifetime cycle option would make the utility_meter integration so much more applicable don't you think?

To compensate for this new sensor, I created an additional lifetime_maximum_power sensor (that's something I'd like to keep an eye on to track what the PV is capable of producing at its maximum).

**Reply by Woetter22** [reply]
> ![image](https://private-user-images.githubusercontent.com/77859037/418174632-9d671a10-f81d-4363-9e16-dbcd35dff3fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA4NDY3MDQsIm5iZiI6MTc0MDg0NjQwNCwicGF0aCI6Ii83Nzg1OTAzNy80MTgxNzQ2MzItOWQ2NzFhMTAtZjgxZC00MzYzLTllMTYtZGJjZDM1ZGZmM2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAxVDE2MjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMDRlYTI3MDRlZmIxZTVlNjI4ZWQwMGYyMTJmOTMxNmM1ODgxNzAzYzJmYzY5MmIyNmU5ZDY0OTViZWE4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-7mCjLXoTRDAsaH646Ak0PRq5-g-0igaqrWaUUfW08)
> 
> Iv'e been using utility_meter sensors (based on the 'Lifetime Energy' ) to calculate daily (but also monthly and yearly) solar usage. So I'm working around the 'Today Energy' being 0 all the time.

How did you get those bars so nicely colored and scaled?

**Reply by TexTown** [reply]
Here's part of the code, it uses a HACS custom card
```
type: vertical-stack
cards:
  - type: custom:bar-card
    height: 25px
    decimal: 1
    max: 50
    positions:
      name: inside
      icon: "off"
    entities:
      - entity: sensor.daily_solar_energy
        color: orange
        name: Vandaag - Zonnepanelen
        icon: mdi:solar-power
      - entity: sensor.daily_energy_production
        color: green
        name: Vandaag - Teruglevering
      - entity: sensor.daily_energy
        color: darkred
        name: Vandaag - Net Gebruik
      - entity: sensor.daily_energy_usage_total
        name: Vandaag - Totaal Gebruik
```

**Reply by TexTown** [reply]
The month and Year blocks have a different 'max'

I use another version of this custom:bar-card to have a visual view of all solar panels as layed out on my roof, showing their current Watt and colourred per inverter. I'll take a screenshot on a sunny day and post it here.

**Comment by HAEdwin** [comment]
@TexTown and @Woetter22 I allready got an anwer from Diogo: "The utility meter can indeed be setup without any cycle, therefore becoming a lifetime sensor. just skip the definition of cycle". 

Considering the above I think a more generic solution is to use the utility_meter. I refer to my comment that I realized the extra lifetime_energy_produced might confuse other users, not adding anything for those with working firmware. So I'd prefer to leave the sensor out. Will that work for you both?

**Reply by Woetter22** [reply]
![image](https://github.com/user-attachments/assets/d9ba1cba-a21b-47e7-a39f-ebada1978482)

Like this?

**Reply by HAEdwin** [reply]
I think input sensor should be the current_power sensor (in configuration.yaml):

```
utility_meter:
  lifetime_energy:
    source: sensor.current_power
```



```
sensor:
  - platform: template
    sensors:
      lifetime_energy_kwh:
        friendly_name: "Lifetime Energy (kWh)"
        unit_of_measurement: "kWh"
        value_template: "{{ states('sensor.lifetime_energy') | float / 1000 }}"
```

I'll give it a try also...
