### DISCUSSION TITLE
Meter (CT-RING) data retrieval possibility ?

### DISCUSSION THREAD

**Discussion by barrets2002** [HAEdwin/homeassistant-apsystems_ecu_reader#30] [Q&A] [answered]
Hello all,

I have an ECU-C and installed CT-Rings to have global power metering. Is it possible to retrieve this information ?

I didn't find the way to do it. 

I have included snapshot of info on ECU http pages.

Thanks, 

Stephane
![Capture d'écran 2025-04-01 180155](https://github.com/user-attachments/assets/66de02f6-9d7d-469f-9fa5-542154bb92a3)
![Capture d'écran 2025-04-01 180136](https://github.com/user-attachments/assets/7a67e233-0883-4db1-b34c-7da6bea4fd93)

**Comment by HAEdwin** [comment, marked as answer]
Since I don't have an ECU-C myself, you'll have to help me find a possible solution. Is there a web page somewhere with current values ​​of the CT rings? The graph you show is compiled based on a data buffer, which URL belongs to it? Are you able to analyze the traffic in the Chrome browser via Ctrl+shift+i and then the network tab? Ideally, I'm looking for something like an APS command to retrieve the values ​​every 5 minutes.

**Comment by barrets2002** [comment]
Hello and thanks for the answer.

I have found this URL :  http://192.168.x.x/index.php/meter/old_meter_power_graph

Which give the  file as an answer :

[old_meter_power_graph.json](https://github.com/user-attachments/files/19602136/old_meter_power_graph.json)

It is used here in this page : view-source:http://192.168.x.x/index.php/meter/meter_power_graph
[http___192.168.x.x_index.php_meter_meter_power_graph.zip](https://github.com/user-attachments/files/19602240/http___192.168.x.x_index.php_meter_meter_power_graph.zip)

by this function : 

function show_graph()
{
	$.ajax({
		url : "http://192.168.x.x/index.php/meter/old_meter_power_graph",
		type : "post",
        dataType : "json",
        data: "date=" + $(".datepicker").val(),
        success : function(Results){
            //整理数据
        	var data_power_1a = new Array();
        	var data_power_1b = new Array();
        	var data_power_1c = new Array(); 
        	var data_power_2a = new Array();
        	var data_power_2b = new Array();
        	var data_power_2c = new Array();   
        	var data_power_3a = new Array();
        	var data_power_3b = new Array();
        	var data_power_3c = new Array();   
        	        	$.each(Results.power1,function(key,value){   
        		data_power_1a.push([value.time,value.powerA]);
        		data_power_1b.push([value.time,value.powerB]);
        		data_power_1c.push([value.time,value.powerC]);
     		});     		       	  	        	    	
        	$.each(Results.power2,function(key,value){   
        		data_power_2a.push([value.time,value.powerA]);
        		data_power_2b.push([value.time,value.powerB]);
        		data_power_2c.push([value.time,value.powerC]);
     		});     		
        	$.each(Results.power2,function(key,value){   
            	var temp1=value.powerA+data_power_1a[key][1];
            	var temp2=value.powerB+data_power_1b[key][1];
            	var temp3=value.powerC+data_power_1c[key][1];
        		data_power_3a.push([value.time,temp1]);
        		data_power_3b.push([value.time,temp2]);
        		data_power_3c.push([value.time,temp3]);
     		});     		
     		
     		//重新绘制图表
            $('#myChart').highcharts({
                subtitle: {
                	text: Results.subtitle
                },
                legend:{
                    layout:'vertical',
                    align:'right',
                    verticalAlign:'middle',
                    borderWidth: 0
                        },
                series:[
                {
                    name: 'Produced A',    
                    data: data_power_1a
                },
                {
                    name: 'Produced B',    
                    data: data_power_1b
                },
                {
                    name: 'Produced C',    
                    data: data_power_1c
                },
                {
                    name: 'Consumed A',    
                    data: data_power_3a
                },
                {
                    name: 'Consumed B',    
                    data: data_power_3b
                },
                {
                    name: 'Consumed C',    
                    data: data_power_3c
                },
                {
                    name: 'Imported/Exported A',    
                    data: data_power_2a
                },
                {
                    name: 'Imported/Exported B',    
                    data: data_power_2b
                },
                {
                    name: 'Imported/Exported C',    
                    data: data_power_2c
                }
                
                
                ]
            });
            //显示发电量
            $('#total').text("Solar Generated Today: " + Results.today_energy + " kWh");
        },
        error : function() { alert("Error"); }
    })
}

**Reply by HAEdwin** [reply]
From the old_meter_power_graph.json - when I break that down to the latest values (also seem to be generated with a 5 minute interval): `{"power1":[{"time":1743760623000,"powerA":5907,"powerB":0,"powerC":0}],"power2":[{"time":1743760623000,"powerA":-2769,"powerB":0,"powerC":0}],"today_energy":"0","subtitle":""}`

So the data represents the today energy but when I sample the latest it represents the current power used from the grid (power2) and current power from the PV (power1). You have two rings so it seems to cover one out of three phases (powerA) on both circuits so
`consumed power in kW on phaseA = power2 + power1`

Are the labels power1 and power2 self configured or are they normally labeled for example "Grid CT" and "Production CT"?
I suppose "powerA", "powerB" and "powerC" are fixed labels.

**Reply by barrets2002** [reply]
At home, I have only one phase :D 

I can have up to 6 CT rings : 
- 3x Grid CT : it is the label on the ECU
- 3x Production CT : it is the label on the ECU
Here are physical images : 
![Production CT](https://github.com/user-attachments/assets/a507ad33-6d40-44e3-9dce-fb484cebd56a)
![Grid CT](https://github.com/user-attachments/assets/eed762a9-3733-4ab1-90f8-dfb2f1dac8df)

So A, B and C correspnd to physical label on the ECU.

The name that I have on the web page of the ECU is : 

- Produced A : Power1 : power A
- Produced B :  Power1 : power B
- Produced C :  Power1 : power C
- Imported/Exported A : Power2 : power A
- Imported/Exported B : Power2 : power B
- Imported/Exported C : Power2 : power C

**Reply by HAEdwin** [reply]
Ok, and besides "old_meter_power_graph.json" there is no other way to retrieve the latest individual values ​​separately?

**Reply by rissson** [reply]
I'll cross-link https://github.com/HAEdwin/homeassistant-apsystems_ecu_reader/discussions/18 as I have also provided some data over there

**Reply by barrets2002** [reply]
I have another page with this king of information, same old page : 
![energy](https://github.com/user-attachments/assets/05403bac-c38d-471c-a354-f516fca07a94)

I have a difference in the post here is the post : 
url : "http://192.168.11.165/index.php/meter/old_meter_energy_graph",
		type : "post",
        dataType : "json",
        data: "date=" + $(".datepicker").val() 
          + "&period=" + data_period,

With : 

var data_period = 'weekly'; //默认查询一周
function select_period(period)
{
	if(period == 'yearly'){
	    $("#show_period").html("Current Year");
	}
	else if(period == 'monthly'){
	    $("#show_period").html("Current Month");
	}
	else{
		$("#show_period").html("Current Week");
	}
	data_period = period;
    show_graph();
}


Whereas for the other one I have (no period here) : 
url : "http://192.168.11.165/index.php/meter/old_meter_power_graph",
		type : "post",
        dataType : "json",
        data: "date=" + $(".datepicker").val(),

**Reply by rissson** [reply]
Here's what I currently have in my conf to retrieve the data.

---

For instant power consumption:
```yaml
rest:
  - resource: http://172.29.192.67/index.php/meter/old_meter_power_graph
    scan_interval: 300
    sensor:
      - unique_id: apsystems_ecu_c_power_meter_produced_a
        name: "APSystems ECU-C Power Meter - Produced - A"
        value_template: "{{ value_json.power1[-1].powerA }}"
        unit_of_measurement: W
        device_class: power
        state_class: measurement
      - unique_id: apsystems_ecu_c_power_meter_produced_b
        name: "APSystems ECU-C Power Meter - Produced - B"
        value_template: "{{ value_json.power1[-1].powerB }}"
        unit_of_measurement: W
        device_class: power
        state_class: measurement
      - unique_id: apsystems_ecu_c_power_meter_produced_c
        name: "APSystems ECU-C Power Meter - Produced - C"
        value_template: "{{ value_json.power1[-1].powerC }}"
        unit_of_measurement: W
        device_class: power
        state_class: measurement
      - unique_id: apsystems_ecu_c_power_meter_imported_exported_a
        name: "APSystems ECU-C Power Meter - Imported/Exported - A"
        value_template: "{{ value_json.power2[-1].powerA }}"
        unit_of_measurement: W
        device_class: power
        state_class: measurement
      - unique_id: apsystems_ecu_c_power_meter_imported_exported_b
        name: "APSystems ECU-C Power Meter - Imported/Exported - B"
        value_template: "{{ value_json.power2[-1].powerB }}"
        unit_of_measurement: W
        device_class: power
        state_class: measurement
      - unique_id: apsystems_ecu_c_power_meter_imported_exported_c
        name: "APSystems ECU-C Power Meter - Imported/Exported - C"
        value_template: "{{ value_json.power2[-1].powerC }}"
        unit_of_measurement: W
        device_class: power
        state_class: measurement
sensor:
  - platform: min_max
    unique_id: apsystems_ecu_c_power_meter_imported_exported
    name: "APSystems ECU-C Power Meter - Imported/Exported"
    type: sum
    round_digits: 3
    entity_ids:
      - sensor.apsystems_ecu_c_power_meter_imported_exported_a
      - sensor.apsystems_ecu_c_power_meter_imported_exported_b
      - sensor.apsystems_ecu_c_power_meter_imported_exported_c
  - platform: min_max
    unique_id: apsystems_ecu_c_power_meter_produced
    name: "APSystems ECU-C Power Meter - Produced"
    type: sum
    round_digits: 3
    entity_ids:
      - sensor.apsystems_ecu_c_power_meter_produced_a
      - sensor.apsystems_ecu_c_power_meter_produced_b
      - sensor.apsystems_ecu_c_power_meter_produced_c
```
Just after midnight, those fail as `powerX[-1]` is non existant, but otherwise this works fine.

---

For energy readings, I have this:

```yaml
rest:
  - resource: http://172.29.192.67/index.php/meter/old_meter_energy_graph
    scan_interval: 300
    sensor:
      - unique_id: apsystems_ecu_c_energy_meter_produced
        name: "APSystems ECU-C Energy Meter - Produced"
        value_template: "{{ value_json.energy1[-1].energy }}"
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
      - unique_id: apsystems_ecu_c_energy_meter_imported_exported_raw
        name: "APSystems ECU-C Energy Meter - Imported/Exported - Raw"
        value_template: "{{ value_json.energy2[-1].energy }}"
        unit_of_measurement: kWh
        state_class: measurement
template:
  - unique_id: apsystems_ecu_c_energy_meter_imported_exported
    sensor:
      - name: "APSystems ECU-C Energy Meter - Imported/Exported"
        state: |
          {% if now().hour == 0 and now().minute <= 10 %}
          0
          {% else %}
          {{ states('sensor.apsystems_ecu_c_energy_meter_imported_exported_raw') | float }}
          {% endif %}
        unit_of_measurement: kWh
        device_class: energy
        state_class: total
        last_reset: "{{ today_at() }}"
    trigger:
      - trigger: time
        at: "00:00:00"
      - trigger: state
        entity_id: sensor.apsystems_ecu_c_energy_meter_imported_exported_raw
  - unique_id: apsystems_ecu_c_energy_meter_imported_exported_inverted
    sensor:
      - name: "APSystems ECU-C Energy Meter - Imported/Exported - Inverted"
        state: |
          {% if now().hour == 0 and now().minute <= 10 %}
          0
          {% else %}
          {{ states('sensor.apsystems_ecu_c_energy_meter_imported_exported_raw') | float * -1 }}
          {% endif %}
        unit_of_measurement: kWh
        device_class: energy
        state_class: total
        last_reset: "{{ today_at() }}"
    trigger:
      - trigger: time
        at: "00:00:00"
      - trigger: state
        entity_id: sensor.apsystems_ecu_c_energy_meter_imported_exported_raw
utility_meter:
  apsystems_ecu_c_energy_meter_imported:
    source: sensor.apsystems_ecu_c_energy_meter_imported_exported
    unique_id: apsystems_ecu_c_energy_meter_imported
    name: "APSystems ECU-C Energy Meter - Imported"
    cycle: daily
    delta_values: false
    net_consumption: false
    periodically_resetting: true
  apsystems_ecu_c_energy_meter_exported:
    source: sensor.apsystems_ecu_c_energy_meter_imported_exported_inverted
    unique_id: apsystems_ecu_c_energy_meter_exported
    name: "APSystems ECU-C Energy Meter - Exported"
    cycle: daily
    delta_values: false
    net_consumption: false
    periodically_resetting: true
```

This works pretty fine, except for the resetting at midnight part. For some reason, the non-inverted sensor resets fine, however the inverted one resets a bit too late and causes the utility meter to jump up by the value it resets to, which in turns causes a peak consumption at midnight of several kWh, which obviously didn't happen. I've been resetting those values manually from the HA developer tools, but it's definitely not ideal.
