### DISCUSSION TITLE
Use the modern configuration

### DISCUSSION THREAD

**Discussion by c0mplex1** [HAEdwin/homeassistant-apsystems_ecu_reader#36] [General]
Please review the examples in the readme documentation.
These examples are still based on the legacy configuration, instead of the supported modern configuration.

**In case of ECU firmware issues**
```
utility_meter:
  lifetime_energy:
    source: sensor.ecu_xxxxxxxxxxxx_current_power

template:
  - sensor:
      - name: "Lifetime Energy (kWh)"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.lifetime_energy')|float(0) / 1000 }}"
```

**The temperature sensors**
```
template:
  - sensor:
      - name: "Temperature non numeric 4080xxxxxxxx"
        state: "{{ states('sensor.inverter_4080xxxxxxxx_temperature')|float(0) }}"
        unit_of_measurement: "°C"

      - name: "Temperature non numeric 8060xxxxxxxx"
        state: "{{ states('sensor.inverter_8060xxxxxxxx_temperature')|float(0) }}"
        unit_of_measurement: "°C"
```
