### ISSUE TITLE
Not all inverters are switching on/off

### ISSUE THREAD

**Issue by JTBitsolutions** [HAEdwin/homeassistant-apsystems_ecu_reader#60]
Thanks voor this integration!

i created an automation to turn my inverters off/on based on the electricity price. in v2.8.0 the switch to switch all inverters off is removed. i configured them in a group and tried to do it individually, but for some reason when i use the switch from the inverter itself instead of the switch of the ECU, some of the inverters are not turning on/off. which inverter is not turning on/off is different everytime.

Is there a way to solve this, or at least some way the ECU can communicate with home assistant that not all inverters are on/off?

## Home Assistant hardware
- [ ] Raspberry Pi
- [ ] Docker container
- [X] Virtual Machine
- [ ] Other

## ECU type
- [ ] ECU-B
- [ ] ECU-R (2160 series)
- [ ] ECU-R-Pro (2162 series)
- [X] ECU-C
- [ ] ECU-3

## ECU is connected by
- [X] Ethernet cable
- [ ] Wireless

## Inverter type(s) used
- [X] DS3 series
- [ ] QS series
- [ ] QT series
- [ ] YC series

APsystems ECU Reader software currently installed
2.8.0

**Comment by HAEdwin** [comment]
The integration indeed does not support the use of a group switch helper. When switching multiple inverters on or off, you should insert a 10 second pause in the automation between switching each inverter on or off. This should help the ECU processing the commands and awaiting response on each toggle of the switch. 

A possible solution is to create a group button entity in the integration.

**Comment by RonaldBoere** [comment]
Hello @HAEdwin,

Nice integration! I have implemented this for an ECU-R 2162, to switch on/off QT2 inverters based on dynamic prices. It works fine!
At the moment I will implement this integration for myself into an ECU-R 2160 with DS3 inverters. Unfortunately, in my opinion it's not possible to switch on/off the inverters with an ECU-R 2160 with this integration.
(ECU-R 2160 also don't have a webinterface)

Manual test:
I setup a modbus TPC connection with an app (Mtcp) on my iphone / or laptop with a modbus tool. Writing 0 to modbus address 40188 will turn off the inverters. Writing 1 to modbus address will start the inverters.
I was surprised that there's a long delay between writing command and the result. It takes approx. 3 minutes.
(i measured the amps produced by the PV system, after 3 minutes, the PV systeems is on or off).

The conclusion is that the manual commands are the right commands. (writing 1 or 0 to address 40188 is working to switch on/off the PV system)

Automation Home Assistant:
I tried to setup a modbus.yaml file and now I can read the parameters from the ECU-R 2160 with modbus TCP.
For example Voltage, Temperature, Power etc. So far so good.
------------------------------------------
Modbus.yaml below, with address 40188.

- name: aps_ecu
  type: tcp
  host: 192.168.2.22
  port: 502
  delay: 5
  message_wait_milliseconds: 100
  timeout: 5
  sensors:
      - name: PV_Connection_Onder
        address: 40188
        slave: 1
        input_type: holding
        data_type: int16
        unique_id: PV_Connection_Onder
-----------------------------------------------

Sometimes I get the problem that entities are "not available". And also writing a 1 or 0 to address 40188 is not working.

Script:

sequence:
  - action: modbus.write_register
    data:
      hub: aps_ecu
      address: 40188
      slave: 1
      value: 0
alias: Omvormers_uitschakelen
description: ""

I expect that I have some timing issues or time outs. 

Please can you give me some advice how to setup a correct modbus communication, or is there another method to switch on/off the PV systeem with a ECU-R 2160 and DS3.

Thanks in advance!

**Comment by HAEdwin** [comment]
@RonaldBoere A bit off-topic, but I agree with you that a modbus integration could be a better choice, although the ECU-B will then be a bit behind.

**Comment by HAEdwin** [comment]
@c0mplex1 and @JTBitsolutions I will try to include an extra control line for each on/off status to make sure the signal has been received and processed correctly. Then that can be included in switching all inverters on or off. After that I think I will delve into modbus.

**Comment by HAEdwin** [comment]
@c0mplex1 @JTBitsolutions I hope v.2.8.1 will improve switching the inverters on or off. When the ECU returns "See the results 5 minutes later !" you could assume that the command was sent successfully. If this method is not reliable, then something else needs to be thought of, such as issuing a modbus command or reading the register afterwards to check if it was set successfully.

**Comment by jeroenleenarts** [comment]
This is the yaml I use for switching my inverters.

```
  - entity_id:
      - sensor.current_electricity_market_price
    trigger: state
conditions:
  - condition: sun
    before: sunset
    after: sunrise
actions:
  - if:
      - condition: numeric_state
        entity_id: sensor.current_electricity_market_price
        below: 0
    then:
      - condition: state
        entity_id: switch.inverter_704000xxxxxx_on_off
        state: "on"
      - metadata: {}
        data: {}
        target:
          entity_id:
            - switch.inverter_704000xxxxxx_on_off
            - switch.inverter_704000xxxxxx_on_off
            - switch.inverter_704000xxxxxx_on_off
            - switch.inverter_704000xxxxxx_on_off
        action: switch.turn_off
      - metadata: {}
        data:
          title: Solar OFF
          message: Energy price is negative
        action: notify.mobile_app_iphone_van_jeroen_leenarts
    else:
      - condition: state
        entity_id: switch.inverter_704000xxxxxx_on_off
        state: "off"
      - metadata: {}
        data: {}
        target:
          entity_id:
            - switch.inverter_704000xxxxxx_on_off
            - switch.inverter_704000xxxxxx_on_off
            - switch.inverter_704000xxxxxx_on_off
            - switch.inverter_704000xxxxxx_on_off
        action: switch.turn_on
      - metadata: {}
        data:
          title: Solar ON
          message: Energy price is positive
        action: notify.mobile_app_iphone_van_jeroen_leenarts
mode: single
```

Before the 2.8.0 update, sometimes one inverter would not toggle on successfully again. Easily fixed with a manual off and on command through Home Assistant.

Since 2.8.0 I haven't had issues yet. (2 occasions)

@HAEdwin, do you still recommend the 10 second delay between on/off commands you suggested?
